// About.jsx explains the project architecture and prediction target.
function About() {
  return (
    <section>
      <div className="page-heading">
        <p className="eyebrow">Project Architecture</p>
        <h1>About LankaHomeValue</h1>
        <p>
          LankaHomeValue is a final year project that combines a React frontend,
          Express backend, FastAPI machine learning API, and a trained house price
          prediction model.
        </p>
      </div>

      <div className="architecture-grid">
        <div className="info-card">
          <span className="step-number">1</span>
          <h2>React Frontend</h2>
          <p>Collects house details from the user and displays prediction results.</p>
        </div>

        <div className="info-card">
          <span className="step-number">2</span>
          <h2>Express Backend</h2>
          <p>Receives frontend requests, calls FastAPI, and saves history in MongoDB.</p>
        </div>

        <div className="info-card">
          <span className="step-number">3</span>
          <h2>FastAPI ML API</h2>
          <p>Loads the trained model and predicts the house selling price.</p>
        </div>

        <div className="info-card">
          <span className="step-number">4</span>
          <h2>Trained Model</h2>
          <p>Predicts the target column: house_selling_price_lkr.</p>
        </div>
      </div>

      <div className="notice-card">
        <h2>Important Note</h2>
        <p>
          The predicted value is an estimate generated by a machine learning model.
          It should not be treated as an official property valuation.
        </p>
      </div>
    </section>
  );
}

export default About;
